services:
  backend:
    build:
      context: .
      target: dev
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1g
    networks:
      - chat_network
  postgres:
    image: postgres:16-alpine
    container_name: chat_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat_network

volumes:
  postgres_data:

networks:
  chat_network:
    driver: bridge
