services:
  backend:
    container_name: chat_backend
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
