"""cascade delete reactions

Revision ID: 3d85918e00ea
Revises: 9062de5a3f8f
Create Date: 2026-04-27 19:04:43.150059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d85918e00ea'
down_revision: Union[str, Sequence[str], None] = '9062de5a3f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reactions_sender_id_fkey'), 'reactions', type_='foreignkey')
    op.drop_constraint(op.f('reactions_message_id_fkey'), 'reactions', type_='foreignkey')
    op.create_foreign_key(None, 'reactions', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reactions', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.create_foreign_key(op.f('reactions_message_id_fkey'), 'reactions', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(op.f('reactions_sender_id_fkey'), 'reactions', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###
